# Generated by Django 4.0.3 on 2022-03-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_favorite_advertisments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite_advertisments',
            old_name='ad_id',
            new_name='ad',
        ),
        migrations.RenameField(
            model_name='favorite_advertisments',
            old_name='user_id',
            new_name='user',
        ),
    ]
