# Generated by Django 4.0.3 on 2022-03-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_advertisments_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisments',
            name='city',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='advertisments',
            name='picture',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
