# Generated by Django 4.0.3 on 2022-03-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_advertisments_city_alter_advertisments_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisments',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
