# Generated by Django 3.1.7 on 2022-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_advertisments_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_ads',
            field=models.ManyToManyField(null=True, to='app.Advertisments'),
        ),
    ]
