# Generated by Django 3.1.7 on 2022-03-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user_favourite_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_ads',
            field=models.ManyToManyField(to='app.Advertisments'),
        ),
    ]
