# Generated by Django 3.1.7 on 2022-03-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220328_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite_advertisments',
        ),
    ]
