# Generated by Django 4.0.3 on 2022-04-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_favorite_advertisments'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_categories',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
